#!/bin/sh
sleep 5
mac="$(cat /sys/class/net/eth0/address)"
timeout 1 haveged -F > /dev/null
ssh -i /root/.ssh/unlock_rsa -o "UserKnownHostsFile=/root/.ssh/known_hosts" -o "ConnectTimeout=100" KEYHOST_ADDRESS "$mac"
