#!/bin/sh
PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /usr/bin/ssh ]; then
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/ssh
copy_exec /usr/sbin/haveged
