#!/bin/sh
PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /usr/bin/ssh ]; then
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions

copy_file key /etc/initramfs-tools/root/.ssh/unlock_rsa /root/.ssh/
copy_file key /etc/initramfs-tools/root/.ssh/unlock_rsa.pub /root/.ssh/
copy_file key /etc/initramfs-tools/root/.ssh/known_hosts /root/.ssh/
